<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Sistema_de_Gestão_Escolar</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WinForms" Version="5.0.55" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="29.1.33" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bibilioteca Sistema de Gestão Escolar\Bibilioteca Sistema de Gestão Escolar.csproj" />
  </ItemGroup>

</Project>